# docker-compose.yml

services:
  mysql:
    image: mysql:8.0
    container_name: healthcare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-healthcare_analytics_lab}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/generated_10k_sample_data.sql:/docker-entrypoint-initdb.d/01-oltp.sql
      - ./data/generate_increment_3k_data.sql:/docker-entrypoint-initdb.d/02-oltp-increment.sql
      - ./deliverables/DDL_star_shema.sql:/docker-entrypoint-initdb.d/03-star-ddl.sql
      - ./deliverables/star_schema.sql:/docker-entrypoint-initdb.d/04-star-etl.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-password}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jupyter:
    build: .
    container_name: healthcare-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-healthcare_analytics_lab}

volumes:
  mysql_data:
